# -*- coding: utf-8 -*-
"""Black_Normal_Task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXRtkpE5Rz3jFCGg3Ui-BF1qOMErmNmP
"""

! [ -e /content ] && pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

import fastbook
from fastai.vision.all import *
from fastbook import *

path = Path('/content/gdrive/MyDrive/TaskData1/')

fns = get_image_files(path)
fns

# !unzip /content/gdrive/MyDrive/TaskData1/Black.zip -d /content/gdrive/MyDrive/TaskData1
# !unzip /content/gdrive/MyDrive/TaskData1/Normal.zip -d /content/gdrive/MyDrive/TaskData1

path.ls()

Path.BASE_PATH =path

dblock = DataBlock(
    blocks=(ImageBlock, CategoryBlock),
    get_items = get_image_files,
    get_y =parent_label,
    splitter = RandomSplitter(valid_pct=0.2),
    item_tfms = Resize(256),
    batch_tfms = [*aug_transforms()],
)

dls = dblock.dataloaders(path)

dls.show_batch(max_n=10, nrows=2)

learn = vision_learner(dls, resnet50, metrics=accuracy)

# learn.lr_find()

learn.fine_tune(10, 1e-3)

interp = ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix()

upload = widgets.FileUpload()
upload

img = PILImage.create(upload.data[-1])
img.to_thumb(256)

pred, idx, prob = learn.predict(upload.data[-1])
print(f' {pred} - {prob[idx]}')

learn.export(path/'black_normal_classifier_test.pkl')

"""

---"""

! [ -e /content ] && pip install -Uqq fastbook
import fastbook
fastbook.setup_book() 
from fastai.vision.all import *
from fastbook import *

path = Path('/content/gdrive/MyDrive/TaskData1')

path.ls(file_exts='.pkl')

load_info = load_learner(path/'black_normal_classifier_test.pkl')

file = widgets.FileUpload()
file

img = PILImage.create(file.data[-1])
img.to_thumb(200)

pred,idx,prob = load_info.predict(file.data[-1])
pred, prob[idx]